import express from 'express';
import { body } from 'express-validator';
import { register, login, adminLogin, me } from '../controllers/authController.js';
import protect from '../middleware/authMiddleware.js';
import validate from '../middleware/validateMiddleware.js';
const router=express.Router();
router.post('/register',[body('name').trim().notEmpty(),body('email').isEmail().normalizeEmail(),body('password').isLength({min:6})],validate,register);
router.post('/login',[body('email').isEmail().normalizeEmail(),body('password').notEmpty()],validate,login);
router.post('/admin-login',[body('email').isEmail().normalizeEmail(),body('password').notEmpty()],validate,adminLogin);
router.get('/me',protect,me);
export default router;
